config:
  messages:
    commands:
      help: |
        # Comandos disponibles
      list:
        - - "`/h`"
          - "muestra esta ayuda"
        - - "`/st`"
          - "muestra estado de agentes"
        - - "`/start`"
          - "inicia un agente `/start <agente>`"
        - - "`/stop`"
          - "detiene un agente `/stop <agente>`"
        - - "`/restart`"
          - "reinicia un agente `/restart <agente>`"
        - - "`/md`"
          - "activa/desactiva markdown `/md on|off`"
        - - "`/q`"
          - "sale del programa"
